#config_version=5

flippers:
  left_flipper:
   main_coil: c_left_flipper
   activation_switch: s_left_flipper_button
   enable_events: machine_reset_phase_3
  right_flipper:
    main_coil: c_right_flipper
    activation_switch: s_right_flipper_button
    enable_events: machine_reset_phase_3
coils:
  c_trough:
    number: 8-1
  c_auto_plunger:
    number: 8-4
  c_left_flipper:
    number: 8-5
    allow_enable: true
    default_hold_power: 0.125
  c_right_flipper:
    number: 8-0
    allow_enable: true
    default_hold_power: 0.125
  c_left_slingshot:
    number: 8-3
  c_right_slingshot:
    number: 8-2
  c_shaker_motor:
    number: 1-0
  c_right_scoop:
    number: 8-8
  c_center_drop_target_down:
    number: 8-7
  c_center_drop_target_up:
    number: 8-6
  c_left_pop_bumper:
    number: 9-2
  c_right_pop_bumper:
    number: 9-3
  c_bottom_pop_bumper:
    number: 9-4
  c_orbit_control_gates:
    number: 9-0
  c_groot_trough_eject:
    number: 9-1
  c_top_magnet:
    number: 9-6
  c_kickback:
    number: 9-8

switches:
  s_left_outlane:
    number: 8-17
  s_left_return_lane_left:
    number: 8-18
  s_left_return_lane_right:
    number: 8-21
  s_right_return_lane:
    number: 8-19
  s_right_outlane:
    number: 8-20
  s_left_slingshot:
    number: 8-30
  s_right_slingshot:
    number: 8-29
  s_left_flipper_button:
    number: 8-25
    tags: left_flipper
  s_right_flipper_button:
    number: 8-24
    tags: right_flipper
  s_left_flipper_eos:
    number: 8-16
  s_right_flipper_eos:
    number: 8-31
  s_trough_6:
    number: 8-32
    type: NC
  s_trough_5:
    number: 8-33
    type: NC
  s_trough_4:
    number: 8-34
    type: NC
  s_trough_3:
    number: 8-35
    type: NC
  s_trough_2:
    number: 8-36
    type: NC
  s_trough_1:
    number: 8-37
    type: NC
  s_trough_jam:
    number: 8-38
    type: NC
  s_shooter_lane:
    number: 8-28
  s_left_lane:
    number: 9-26
  s_left_lane_target:
    number: 9-27
  s_guardians_target_top:
    number: 9-20
  s_guardians_target_bottom:
    number: 9-21
  s_left_orbit:
    number: 9-8
  s_kickback_opto:
    number: 9-23
    type: NC
  s_left_ramp_exit:
    number: 9-12
    type: NC
  s_groot_target_left:
    number: 9-10
  s_groot_target_right:
    number: 9-11
  s_groot_opto:
    number: 9-0
    type: NC
  s_groot_trough_1:
    number: 9-1
    type: NC
  s_groot_trough_2:
    number: 9-2
    type: NC
  s_groot_trough_3:
    number: 9-3
    type: NC
  s_groot_trough_4:
    number: 9-4
    type: NC
  s_groot_motor_away:
    number: 9-5
  s_groot_motor_home:
    number: 9-6
  s_center_drop_target:
    number: 8-9
    type: NC
  s_orb_standup_target:
    number: 8-12
  s_right_orbit:
    number: 9-9
  s_right_ramp_exit:
    number: 9-13
    type: NC
  s_left_pop_bumper:
    number: 9-28
  s_right_pop_bumper:
    number: 9-29
  s_bottom_pop_bumper:
    number: 9-30
  s_top_lane_left:
    number: 9-31
  s_top_lane_right:
    number: 9-16
  s_hadron_enforcer_target_1:
    number: 9-17
  s_hadron_enforcer_target_2:
    number: 9-18
  s_hadron_enforcer_target_3:
    number: 9-19
  s_hadron_enforcer_target_4:
    number: 8-14
  s_hadron_enforcer_target_5:
    number: 8-15
  s_right_scoop:
    number: 8-8
  s_lockdown_button:
    number: 1-2
  s_start_button:
    number: 1-11
  s_tournament_start_button:
    number: 1-12
  s_left_coin:
    number: 1-16
  s_right_coin:
    number: 1-18
  s_center_coin:
    number: 1-17
  s_tilt_pendulum:
    number: 1-14
  s_slam_tilt:
    number: 1-22
  s_service_plus:
    number: 0-9
  s_service_minus:
    number: 0-10
  s_service_back:
    number: 0-11
  s_service_select:
    number: 0-8

lights:
  l_backlight:
    number: 0-0
  l_coin_enable:
    number: 1-0
  l_start_button:
    number: 1-2
  l_tourney_start_button:
    number: 1-3
  l_lockdown_bar:
    channels:
      red:
        number: 1-5
      green:
        number: 1-4
      blue:
        number: 1-7
  l_left_outlane:
    number: 9-51
  l_left_return_lane_left:
    number: 9-52
  l_left_return_lane_right:
    number: 9-53
  l_antiquities_shop:
    number: 8-20
  l_pod_chase:
    number: 8-21
  l_sanctuary:
    number: 8-23
  l_yaka_arrow:
    number: 8-16
  l_sibling_rivalry:
    number: 8-19
  l_escape_kyln:
    number: 8-18
  l_knowhere:
    number: 8-17
  l_quills_quest:
    number: 8-15
  l_immolation_initiative:
    number: 8-22
  l_orb_multiball_bottom:
    number: 8-9
  l_save_xandar:
    number: 8-10
  l_groot_multiball_bottom:
    number: 8-13
  l_shoot_again:
    number: 8-11
  l_right_return_lane:
    number: 8-24
  l_right_outlane:
    number: 8-31
  l_left_lane_arrow:
    channels:
      red:
        number: 9-57
      green:
        number: 9-58
      blue:
        number: 9-59
  l_left_lane_x:
    number: 9-63
  l_left_lane_rectangle:
    number: 9-56
  l_guardians_left:
    number: 9-37
  l_guardians_center:
    number: 9-38
  l_guardians_right:
    number: 9-39
  l_left_orbit_arrow:
    channels:
      red:
        number: 9-33
      green:
        number: 9-34
      blue:
        number: 9-35
  l_left_orbit_x:
    number: 9-36
  l_left_orbit_rectangle:
    number: 9-32
  l_rocket_arrow:
    channels:
      red:
        number: 9-43
      green:
        number: 9-44
      blue:
        number: 9-45
  l_rocket_x:
    number: 9-42
  l_rocket_rectangle:
    number: 9-40
  l_rocket_multiball:
    number: 9-47
  l_left_ramp_arrow:
    channels:
      red:
        number: 9-21
      green:
        number: 9-22
      blue:
        number: 9-23
  l_left_ramp_x:
    number: 9-24
  l_left_ramp_rectangle:
    number: 9-25
  l_groot_target_left:
    number: 9-20
  l_groot_target_right:
    number: 9-8
  l_groot_multiball:
    number: 9-16
  l_groot_arrow:
    channels:
      red:
        number: 9-17
      green:
        number: 9-18
      blue:
        number: 9-19
  l_groot_x:
    number: 9-31
  l_groot_rectangle:
    number: 9-30
  l_lock_1:
    number: 9-26
  l_lock_2:
    number: 9-27
  l_lock_3:
    number: 9-28
  l_lock_4:
    number: 9-29
  l_orb_arrow:
    channels:
      red:
        number: 8-45
      green:
        number: 8-46
      blue:
        number: 8-47
  l_orb_x:
    number: 8-51
  l_orb_rectangle:
    number: 8-49
  l_orb_multiball:
    number: 8-48
  l_right_ramp_arrow:
    channels:
      red:
        number: 8-42
      green:
        number: 8-43
      blue:
        number: 8-44
  l_right_ramp_x:
    number: 8-52
  l_right_ramp_rectangle:
    number: 8-50
  l_right_orbit_arrow:
    channels:
      red:
        number: 8-37
      green:
        number: 8-38
      blue:
        number: 8-39
  l_right_orbit_x:
    number: 8-32
  l_right_orbit_rectangle:
    number: 8-40
  l_right_scoop_arrow:
    channels:
      red:
        number: 8-25
      green:
        number: 8-26
      blue:
        number: 8-27
  l_right_scoop_x:
    number: 8-30
  l_right_scoop_rectangle:
    number: 8-29
  l_billboard_1:
    number: 8-33
  l_billboard_2:
    number: 8-34
  l_billboard_3:
    number: 8-35
  l_billboard_4:
    number: 8-36
  l_hadron_enforcer_1:
    number: 9-55
  l_hadron_enforcer_2:
    number: 9-46
  l_hadron_enforcer_3:
    number: 9-41
  l_hadron_enforcer_4:
    number: 8-41
  l_hadron_enforcer_5:
    number: 8-28
  l_left_pop_bumper:
    number: 9-9
  l_right_pop_bumper:
    number: 9-10
  l_bottom_pop_bumper:
    number: 9-11
  l_top_lane_left:
    number: 9-12
  l_top_lane_right:
    number: 9-13
  l_orb:
    channels:
      red:
        number: 8-53
      green:
        number: 8-54
      blue:
        number: 8-55
  l_backpanel_gi:
    number: 9-0
  l_top_gi_1:
    number: 9-1
  l_top_gi_2:
    number: 9-2
  l_yondu_flasher:
    number: 8-5
  l_left_ramp_top_flasher:
    number: 9-3
  l_left_ramp_bottom_flasher:
    number: 8-3
  l_right_ramp_top_flasher:
    number: 9-4
  l_right_ramp_bottom_flasher:
    number: 8-4
  l_pop_bumper_flasher:
    number: 9-5
  l_magnet_flasher:
    number: 9-54
  l_drop_target_flasher:
    number: 9-6

  
  
 
